## All libraries import

In [1]:
import pandas as pd
import numpy as np
import re

## Importing the dataset

In [49]:
world_earthquakes = pd.read_csv('../data/world_earthquakes.csv')
world_earthquakes.head()

date    country latitude longitude depth magnitude  \
0  1900-05-11 17:23      Japan   38.700   141.100     5  7.0 MJMA   
1  1900-07-12 06:25     Turkey   40.300    43.100   NaN   5.9 Muk   
2  1900-10-29 09:11  Venezuela   11.000   -66.000     0    7.7 Mw   
3  1901-02-15 00:00      China   26.000   100.100     0    6.5 Ms   
4  1901-03-31 07:11   Bulgaria   43.400    28.700   NaN   6.4 Muk   

  secondary_effects  pde_shaking_deaths  pde_total_deaths  utsu_total_deaths  \
0               NaN                 NaN               NaN                NaN   
1               NaN                 NaN               NaN              140.0   
2               NaN                 NaN               NaN                NaN   
3               NaN                 NaN               NaN                NaN   
4               NaN                 NaN               NaN                4.0   

  em_dat_total_deaths others_source_deaths  
0                 NaN                  NaN  
1                 NaN                  NaN  
2                 NaN                  NaN  
3                 NaN                  NaN  
4                 NaN                  NaN

In [4]:
world_earthquakes.tail()

date                                   country latitude  \
1335  2011-03-24 20:25         Burma (see 2011 Burma earthquake)      NaN   
1336  2011-04-07 14:32  Japan (see April 2011 Miyagi earthquake)     38.2   
1337  2011-09-18 12:40        India (see 2011 Sikkim earthquake)   27.723   
1338  2011-09-23 10:41          Turkey (see 2011 Van earthquake)     38.6   
1339  2018-08-05 19:46         Indonesia (see Lombok earthquake)      NaN   

     longitude depth magnitude secondary_effects  pde_shaking_deaths  \
1335       NaN   NaN    6.8 Mw               NaN                 NaN   
1336     140.0  66.0    7.1 Mw               NaN                 NaN   
1337    88.064  19.7    6.9 Mw                 L                 NaN   
1338      43.5   7.2    7.1 Mw               NaN                 NaN   
1339       NaN  31.0    6.9 Mw               NaN                 NaN   

      pde_total_deaths  utsu_total_deaths em_dat_total_deaths  \
1335               NaN                NaN                 NaN   
1336               NaN                NaN                 NaN   
1337               NaN                NaN                 NaN   
1338               NaN                NaN                 NaN   
1339               NaN                NaN                 NaN   

              others_source_deaths  
1335                          150+  
1336                           NaN  
1337                          111+  
1338  601 (as of October 30, 2011)  
1339                           NaN

In [48]:
world_earthquakes.shape

(1340, 12)

## 1/ Change NaN for 0 in integer columns "others_source_deaths", "em_dat_total_deaths", "utsu_total_deaths", "pde_total_deaths", "pde_shaking_deaths":

In [50]:
world_earthquakes['others_source_deaths'] = world_earthquakes['others_source_deaths'].fillna(0)
world_earthquakes['em_dat_total_deaths'] = world_earthquakes['em_dat_total_deaths'].fillna(0)
world_earthquakes['utsu_total_deaths'] = world_earthquakes['utsu_total_deaths'].fillna(0)
world_earthquakes['pde_total_deaths'] = world_earthquakes['pde_total_deaths'].fillna(0)
world_earthquakes['pde_shaking_deaths'] = world_earthquakes['pde_shaking_deaths'].fillna(0)
world_earthquakes.head()

date    country latitude longitude depth magnitude  \
0  1900-05-11 17:23      Japan   38.700   141.100     5  7.0 MJMA   
1  1900-07-12 06:25     Turkey   40.300    43.100   NaN   5.9 Muk   
2  1900-10-29 09:11  Venezuela   11.000   -66.000     0    7.7 Mw   
3  1901-02-15 00:00      China   26.000   100.100     0    6.5 Ms   
4  1901-03-31 07:11   Bulgaria   43.400    28.700   NaN   6.4 Muk   

  secondary_effects  pde_shaking_deaths  pde_total_deaths  utsu_total_deaths  \
0               NaN                 0.0               0.0                0.0   
1               NaN                 0.0               0.0              140.0   
2               NaN                 0.0               0.0                0.0   
3               NaN                 0.0               0.0                0.0   
4               NaN                 0.0               0.0                4.0   

  em_dat_total_deaths others_source_deaths  
0                   0                    0  
1                   0                    0  
2                   0                    0  
3                   0                    0  
4                   0                    0

## 2/ Change columns "pde_shaking_deaths", "pde_total_deaths", "utsu_total_deaths" into integer:

In [51]:
world_earthquakes['pde_shaking_deaths'] = world_earthquakes['pde_shaking_deaths'].astype(int)
world_earthquakes['pde_total_deaths'] = world_earthquakes['pde_total_deaths'].astype(int)
world_earthquakes['utsu_total_deaths'] = world_earthquakes['utsu_total_deaths'].astype(int)

world_earthquakes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   date                  1340 non-null   object
 1   country               1340 non-null   object
 2   latitude              1325 non-null   object
 3   longitude             1325 non-null   object
 4   depth                 1250 non-null   object
 5   magnitude             1339 non-null   object
 6   secondary_effects     373 non-null    object
 7   pde_shaking_deaths    1340 non-null   int32 
 8   pde_total_deaths      1340 non-null   int32 
 9   utsu_total_deaths     1340 non-null   int32 
 10  em_dat_total_deaths   1340 non-null   object
 11  others_source_deaths  1340 non-null   object
dtypes: int32(3), object(9)
memory usage: 110.0+ KB


In [52]:
world_earthquakes['pde_shaking_deaths'].unique()

array([     0,   2000,     25,      2,     15,     13,     53,     24,
         3000,     12,    136,     14,      1,      3,   1086,    176,
           81,     65,    100,   1000,     83,      5,      7,   5054,
            4,     11,   5000,     17,     26,    600,     10,     27,
           78,   5300,     47,   2311,  23000,     49,      8,    900,
            6,    422,    563, 655237,      9,    133,    167,     30,
          348,     70,    584,     21,     22,     50,  15000,     76,
          200,     18,    156,     37,     41,    280,     52,     60,
          188,    300,    305,    150,     16,   1500,    220,     43,
         2800,    450,    104,   1342,     34,    443,     20,    177,
           23,     71,   9500,     29,    950,    998,    730,  25000,
           62,    126,    135,  45000,   1621,     19,     75,    114,
          498,     36,     61,    552,   9748,    295,    159,   5502,
           42,   1989,    101,     84,    322,    108,   1100,   1572,
      

## 3/ Change columns "latitude", "longitude" and "depth" in float:

In [53]:
world_earthquakes[world_earthquakes['latitude'] == '?']

date                                 country latitude  \
413  1963-06-26 04:17  Macedonia (see 1963 Skopje earthquake)        ?   

    longitude depth magnitude secondary_effects  pde_shaking_deaths  \
413        ??     ?    6.1 Mw               NaN                   0   

     pde_total_deaths  utsu_total_deaths em_dat_total_deaths  \
413              1100                  0                   0   

    others_source_deaths  
413                    0

First problem = need to get rid of "?"

### Latitude column:

In [56]:
# I found the info online for this specific event so I added the latitude
world_earthquakes["latitude"] = world_earthquakes["latitude"].replace("?", 42.100)
world_earthquakes['latitude'] = world_earthquakes['latitude'].astype(float)

### Longitude column:

In [57]:
# I found the info online for this specific event so I added the longitude
world_earthquakes["longitude"] = world_earthquakes["longitude"].replace("??", 21.400)
world_earthquakes['longitude'] = world_earthquakes['longitude'].astype(float)

### Depth column:

In [58]:
# I found the info online for this specific event so I added the depth of 6 km
world_earthquakes['depth'] = world_earthquakes["depth"].replace("?", 6.0)
world_earthquakes['depth'] = world_earthquakes['depth'].astype(float)
world_earthquakes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   date                  1340 non-null   object 
 1   country               1340 non-null   object 
 2   latitude              1325 non-null   float64
 3   longitude             1325 non-null   float64
 4   depth                 1250 non-null   float64
 5   magnitude             1339 non-null   object 
 6   secondary_effects     373 non-null    object 
 7   pde_shaking_deaths    1340 non-null   int32  
 8   pde_total_deaths      1340 non-null   int32  
 9   utsu_total_deaths     1340 non-null   int32  
 10  em_dat_total_deaths   1340 non-null   object 
 11  others_source_deaths  1340 non-null   object 
dtypes: float64(3), int32(3), object(6)
memory usage: 110.0+ KB


## 4/ Remove the footnote from the column "em_dat_total_deaths"

In [59]:
world_earthquakes.columns.unique()

Index(['date', 'country', 'latitude', 'longitude', 'depth', 'magnitude',
       'secondary_effects', 'pde_shaking_deaths', 'pde_total_deaths',
       'utsu_total_deaths', 'em_dat_total_deaths', 'others_source_deaths'],
      dtype='object')

### NB: What I'm targeting is '10[7]|' and I want to get '10' instead, this is the only thing to change in this column:

In [60]:
world_earthquakes['em_dat_total_deaths'].unique()

array([0, '2000', '20000', '2500', '400', '12000', '75000', '923', '20',
       '29980', '1800', '10000', '100', '116', '180000', '1000', '5000',
       '143000', '2925', '200000', '107', '3300', '500', '0', '36', '256',
       '6', '3008', '6000', '3410', '60000', '9', '149', '30000', '32962',
       '249', '980', '200', '3000', '213', '1083', '2824', '3959', '998',
       '1961', '4000', '165', '73', '1400', '233', '27', '5131', '110000',
       '8', '437', '1500', '30', '14', '1200', '455', '7', '13', '1250',
       '39', '53', '160', '28', '191', '57', '131', '4', '25', '23', '38',
       '128', '10[7]|', '80', '2394', '120', '61', '54', '183', '240',
       '177', '19', '47', '11', '271', '29', '15', '41', '24', '150',
       '1086', '66794', '176', '65', '878', '85', '5057', '17', '78',
       '2385', '1', '23000', '50', '2', '10', '922', '420', '573',
       '242000', '16', '3840', '1641', '167', '352', '3', '185', '589',
       '21', '25000', '45', '5', '121', '34', '26', '350'

### NB: What didn't work (and I would love some feedback!)

What needs to be removed is [7]| from '10[7]|'


In [61]:
test = '345[7]|'

In [64]:
print(re.split(r"\[\d+]\|", test))

['345', '']


**Feedback: When you run `split()`, the result will always be a list. So you will have to select the item from that returned list using index**

In [65]:
# Like so...
print(re.split(r"\[\d+]\|", test)[0]) # The item we want is the first element of the list

345


The test works? **You will need to use `apply()` with a `lambda` function to make it work. Alternatively, you can use a separate function to replace the lambda function.**

In [92]:
# Using a lambda function
world_earthquakes['test_col'] = world_earthquakes['em_dat_total_deaths'].apply(lambda x: (re.split(r"\[\d+]\|", str(x)))[0])
world_earthquakes[world_earthquakes['em_dat_total_deaths'] == '10[7]|']

date                                    country  latitude  \
439  1966-04-25 23:22  Uzbekistan (see 1966 Tashkent earthquake)       NaN   

     longitude  depth magnitude secondary_effects  pde_shaking_deaths  \
439        NaN    NaN      5 ML               NaN                   0   

     pde_total_deaths  utsu_total_deaths em_dat_total_deaths  \
439                 0                  0              10[7]|   

    others_source_deaths test_col  
439                    0       10

In [93]:
# Lambda is just a shortcut for def
# If using a separate def function... same concept applies
def split_formatting(sstr):
    # Apply the split on the string. The result will be a string
    slist = re.split(r"\[\d+]\|", str(x)) # [10,]
    # The element we want to grab is the first element of that list
    return slist[0]

# Now, we can simply replace the lambda function in apply() with this function

**The idea is that `apply()` will apply this transforming function for every single element in the column and replace each element in the target column with the result**

**Another way you can handle this is simpy using `str.split("[")` and again select only the first element:**

In [95]:
def a_different_split(sstr):
    slist = sstr.split("[") # for 10[7]|, this would result in ["10", "7]|"]
    # Again, we only want to return the first element
    return slist[0]

Let's test this function

In [96]:
a_different_split("10[7]|")

'10'

Again, using `.apply()`, you can apply this to the whole column

---

In [94]:
world_earthquakes[world_earthquakes['em_dat_total_deaths'] == '10[7]|']

date                                    country  latitude  \
439  1966-04-25 23:22  Uzbekistan (see 1966 Tashkent earthquake)       NaN   

     longitude  depth magnitude secondary_effects  pde_shaking_deaths  \
439        NaN    NaN      5 ML               NaN                   0   

     pde_total_deaths  utsu_total_deaths em_dat_total_deaths  \
439                 0                  0              10[7]|   

    others_source_deaths test_col  
439                    0       10

I made a new column to be able to see what I did however looks like I'm getting now '[10,]' and I want only '10'

**Feedback: Again, you just need to select to first element from that returned list. In this case, `'10'` is that first element**

New try:

In [29]:
#world_earthquakes.loc[world_earthquakes['em_dat_total_deaths'] == "10[7]|"] = 10

In [30]:
#world_earthquakes[world_earthquakes['country'] == 'Uzbekistan (see 1966 Tashkent earthquake)']

This function instead of just changing "10[7]|" to "10", just got completely rid of the row!!!!!! 

### NB: What worked but it's not applicable for huge database...

New try:

In [31]:
world_earthquakes["em_dat_total_deaths"] = world_earthquakes["em_dat_total_deaths"].replace("10[7]|", 10)

In [32]:
world_earthquakes[world_earthquakes['country'] == 'Uzbekistan (see 1966 Tashkent earthquake)']

date                                    country  latitude  \
439  1966-04-25 23:22  Uzbekistan (see 1966 Tashkent earthquake)       NaN   

     longitude  depth magnitude secondary_effects  pde_shaking_deaths  \
439        NaN    NaN      5 ML               NaN                   0   

     pde_total_deaths  utsu_total_deaths em_dat_total_deaths  \
439                 0                  0                  10   

    others_source_deaths  
439                    0

Not the best solution but it worked!!!! I'm open to suggestions!

In [33]:
world_earthquakes['em_dat_total_deaths'].unique()

array([0, '2000', '20000', '2500', '400', '12000', '75000', '923', '20',
       '29980', '1800', '10000', '100', '116', '180000', '1000', '5000',
       '143000', '2925', '200000', '107', '3300', '500', '0', '36', '256',
       '6', '3008', '6000', '3410', '60000', '9', '149', '30000', '32962',
       '249', '980', '200', '3000', '213', '1083', '2824', '3959', '998',
       '1961', '4000', '165', '73', '1400', '233', '27', '5131', '110000',
       '8', '437', '1500', '30', '14', '1200', '455', '7', '13', '1250',
       '39', '53', '160', '28', '191', '57', '131', '4', '25', '23', '38',
       '128', 10, '80', '2394', '120', '61', '54', '183', '240', '177',
       '19', '47', '11', '271', '29', '15', '41', '24', '150', '1086',
       '66794', '176', '65', '878', '85', '5057', '17', '78', '2385', '1',
       '23000', '50', '2', '10', '922', '420', '573', '242000', '16',
       '3840', '1641', '167', '352', '3', '185', '589', '21', '25000',
       '45', '5', '121', '34', '26', '350', '60'

## 5/ Remove footnotes from the column "others_source_deaths":

In [34]:
world_earthquakes['others_source_deaths'].unique()

array([0, '3500', '8000+', '46', '164[6]', '1500[6]', '105000', '1404',
       '1', '120', '200', '380', '2041', '33[8]', '45000[9]', '2489[10]',
       '26271[11] 26000[12]', '68', '231000*[13] 283000*[14] 227898*[15]',
       '41', '60[16]', '215', '34', '295', '79', '189', '1115',
       '222,517[17]', '521[19]', '42', '2698', '185', '15894[20]', '150+',
       '111+', '601 (as of October 30, 2011)'], dtype=object)

**Feedback: Same concept as above. You can still use `split()` here again. In this case, the regex option might work better because the split can only be used for one case at a time. With regex, you can setup multiple `or` conditions for the split for the cases for `*`, `[` and `\s(`.**

**Or, you can always use multiple `apply()` with `split()`. The first `apply()` could take care of `*` then the second `apply` for ` (` and so on...**

### Again what didn't work:

In [35]:
test2 = '456 (as of Oct 30, 2011)'

In [36]:
print(re.split(r"\(as of Oct 30, 2011\)", test2))

['456 ', '']


In [37]:
#world_earthquakes['other_col'] = world_earthquakes['others_source_deaths'].str.split(r"\(as of Oct 30, 2011\)")

In [38]:
#world_earthquakes.tail()

This function is working but it is adding square brackets on the numbers so not what I want:
aka: '10[7]' --> '[10, ]' but I want '10'

### To remove * and + in the column "other_source_deaths":

In [39]:
test4 = '8000+, 231000*[13]'

In [40]:
print(re.split(r"[+*]", test4))

['8000', ', 231000', '[13]']


In [41]:
#world_earthquakes['other_col'] = world_earthquakes['others_source_deaths'].str.split(r"[+*]")

In [42]:
#world_earthquakes.tail()

It did get rid of + and * but did put into brackets like: 150+ --> [150,]

In [43]:
# to get the biggest number np.max()

### Again: not the best option but It does clean the column: (I highly open to suggestion!!! but at least we can work with this column now!)

In [44]:
world_earthquakes['others_source_deaths'].unique()

array([0, '3500', '8000+', '46', '164[6]', '1500[6]', '105000', '1404',
       '1', '120', '200', '380', '2041', '33[8]', '45000[9]', '2489[10]',
       '26271[11] 26000[12]', '68', '231000*[13] 283000*[14] 227898*[15]',
       '41', '60[16]', '215', '34', '295', '79', '189', '1115',
       '222,517[17]', '521[19]', '42', '2698', '185', '15894[20]', '150+',
       '111+', '601 (as of October 30, 2011)'], dtype=object)

In [45]:
world_earthquakes["others_source_deaths"] = world_earthquakes["others_source_deaths"].replace("8000+", 8000).replace("164[6]", 164).replace("1500[6]", 1500).replace("33[8]", 33).replace("45000[9]", 45000).replace("2489[10]", 2489).replace("26271[11] 26000[12]", 26271).replace("231000*[13] 283000*[14] 227898*[15]", 283000).replace("60[16]", 60).replace("222,517[17]", 517).replace("521[19]", 521).replace("15894[20]", 15894).replace("150+", 150).replace("111+", 111).replace("601 (as of October 30, 2011)", 601) 

In [46]:
world_earthquakes['others_source_deaths'].unique()

array([0, '3500', 8000, '46', 164, 1500, '105000', '1404', '1', '120',
       '200', '380', '2041', 33, 45000, 2489, 26271, '68', 283000, '41',
       60, '215', '34', '295', '79', '189', '1115', 517, 521, '42',
       '2698', '185', 15894, 150, 111, 601], dtype=object)

## 6/ New df partially cleaned:

In [47]:
world_earthquakes.head()

date    country  latitude  longitude  depth magnitude  \
0  1900-05-11 17:23      Japan      38.7      141.1    5.0  7.0 MJMA   
1  1900-07-12 06:25     Turkey      40.3       43.1    NaN   5.9 Muk   
2  1900-10-29 09:11  Venezuela      11.0      -66.0    0.0    7.7 Mw   
3  1901-02-15 00:00      China      26.0      100.1    0.0    6.5 Ms   
4  1901-03-31 07:11   Bulgaria      43.4       28.7    NaN   6.4 Muk   

  secondary_effects  pde_shaking_deaths  pde_total_deaths  utsu_total_deaths  \
0               NaN                   0                 0                  0   
1               NaN                   0                 0                140   
2               NaN                   0                 0                  0   
3               NaN                   0                 0                  0   
4               NaN                   0                 0                  4   

  em_dat_total_deaths others_source_deaths  
0                   0                    0  
1                   0                    0  
2                   0                    0  
3                   0                    0  
4                   0                    0

## 7/ There is still "country", "magnitude", "secondary_effects" to clean! And maybe date as well?